all:
  children:
    wolf_nodes:
      hosts:
        wolf-debian:
          ansible_host: 10.33.214.128
          ansible_user: root
          ansible_python_interpreter: /bin/python3
        wolf-rocky:
          ansible_host: 10.33.214.248
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        wolf-alma:
          ansible_host: 10.33.214.189
          ansible_user: root
          ansible_python_interpreter: /bin/python3

